#!/bin/bash
# Instructions to fix Railway service

echo "=== Fix Railway Config Steps ==="
echo ""
echo "1. Link to your service:"
echo "   railway link"
echo "   Select project: openclaw"
echo "   Select service: 010423f7-b406-4cd9-83f1-16b9d8b9c4d2"
echo "   Select environment: production"
echo ""
echo "2. Temporarily use debug Dockerfile:"
echo "   railway up -d --dockerfile Dockerfile.debug"
echo ""
echo "3. Wait for deployment, then SSH in:"
echo "   railway run bash"
echo ""
echo "4. Edit the config file:"
echo "   vi /data/.openclaw/openclaw.json"
echo "   # OR use nano if you prefer:"
echo "   nano /data/.openclaw/openclaw.json"
echo ""
echo "5. Find and fix 'maxSpawnDepth' value (should be a number like 3 or 5)"
echo ""
echo "6. Exit the SSH session (Ctrl+D)"
echo ""
echo "7. Switch back to normal Dockerfile:"
echo "   railway up -d"
echo ""
echo "=== Alternative: Railway Dashboard Method ==="
echo ""
echo "1. Go to your Railway project dashboard"
echo "2. Settings > Deploy from GitHub > Change 'Dockerfile Path' to 'Dockerfile.debug'"
echo "3. Deploy"
echo "4. Once running, use 'Connect' > 'SSH' from dashboard"
echo "5. Edit /data/.openclaw/openclaw.json"
echo "6. Change Dockerfile path back to 'Dockerfile'"
echo "7. Redeploy"
